### ISSUE TITLE
Import Error caused due to named imports

### ISSUE THREAD

**Issue by krishnan2098** [mhnpd/Test#108]
The documentation doesn't clearly mention whether the component has to be imported as a named import. And the Typescript example screenshot still shows that the right way to import a component is using `import Loader from "react-loader-spinner"` while there is no export in **index.ts.js** by the name **Loader.** The correct way to import the module is to use `import { Oval } from "react-loader-spinner"` It would be great to update the documentation.

**Comment by mhnpd** [comment]
Document is updated
