### ISSUE TITLE
Error while running the loader v.5.0.6

### ISSUE THREAD

**Issue by ImranArtwel** [mhnpd/Test#109]
It seems like there is an import in node_modules for CradleLoader which is breaking.
<img width="692" alt="Screen Shot 2022-01-10 at 10 01 24 AM" src="https://user-images.githubusercontent.com/17822563/148797608-a3d05d4e-e18c-4514-8a34-1c86d7657e04.png">

Looks like the issue is in `CradleLoader.tsx` line 4. May I know why you are importing css on that line.

**Comment by JakobClausen** [comment]
Yes, i have the same issue when using next.js. It worked with Preact Cli on the same version.

**Comment by mhnpd** [comment]
v5.0.7 Fixes it.
