### ISSUE TITLE
Oval spinner is not cropped properly

### ISSUE THREAD

**Issue by wooferzfg** [mhnpd/Test#110]
I ran `react-loader-spinner-example` with the latest version of `react-loader-spinner`, and the Oval spinner has its edges cut off:

![chrome_UxEDUP5v1O](https://user-images.githubusercontent.com/8262173/149819342-daef2547-f330-4b71-9855-bf9b21449b6e.png)

I ran into the same issue with my own project as well.

**Comment by jerryheir** [comment]
I have the same issue

**Comment by SimonNJensen** [comment]
Same issue here. Can't find a way to style my way out of it. The issue is also present on your own Demo page here: https://mhnpd.github.io/react-loader-spinner/oval

**Comment by mhnpd** [comment]
#116 solves it
