### ISSUE TITLE
Treeshaking not really working

### ISSUE THREAD

**Issue by Sysix** [mhnpd/Test#111]
Hello,

my bundle analyzer tells me that the complete Package is still loaded into prod.
I think you need to add `module` in your package.json to tell the bundler it supports it.

![grafik](https://user-images.githubusercontent.com/3897725/149845519-ba518437-96c5-407a-84fe-68e57e5a9bdd.png)

Example code:

```
import { ThreeDots } from "react-loader-spinner";

const Spinner = () => (
    <ThreeDots
        color="#fdc301"
        height="100"
        width="100"
    />
);
```

Versions:
"react": "^16.8.6",
"react-loader-spinner": "^5.0.8",

**Comment by mhnpd** [comment]
What is the best way to achieve this?

**Comment by Sysix** [comment]
Because you are using tslib to generate your files, I guess replacing `"module": "commonjs"` to `"module": "es6"` or `es2020`.
I think the CLI also allows  to override it :)

I dont really have enough expertise to help you on this path. Maybe look at the following package how they solved that:
- https://github.com/jquense/yup
- https://github.com/reactjs/react-transition-group

**Comment by Sysix** [comment]
@mhnpd Version 5.0.10 doesnt fix the problem.

**Comment by wooferzfg** [comment]
I'm not sure that 5.0.10 was actually built with `"module": "es6"` even though that change was made? Looking at `node_modules\react-loader-spinner\dist\loader\Audio.js`, it includes the line:
```
# This is what you get when you build with "module": "commonjs"
__importDefault(require("react"));
```
instead of:
```
# This is what you get when you build with "module": "es6"
import React from 'react';
```
