### ISSUE TITLE
Spelling error in CradleLoader and in baseprops typedef

### ISSUE THREAD

**Issue by rschalo** [mhnpd/Test#112]
Hello Team,

I believe that there is a spelling error for `ariaLabel` in `baseprops` in `src/type.ts`.

This also shows up in the props def for `CradleLoader` and `Audio`, I'm willing to look into other components as well.

Would you like to me make a fix and open a PR?

Best,
Reed

**Comment by mhnpd** [comment]
V5.0.9 solves the typo.
