### ISSUE TITLE
Please check exports and imports fields in package.json, because they fail to build.

### ISSUE THREAD

**Issue by KostiantynO** [mhnpd/Test#118]
Module not found: Error: Package path ./dist/loader/css/react-spinner-loader.css is not exported from package /home/runner/work/goit-react-hw-04-hooks-images/goit-react-hw-04-hooks-images/node_modules/react-loader-spinner (see exports field in /home/runner/work/goit-react-hw-04-hooks-images/goit-react-hw-04-hooks-images/node_modules/react-loader-spinner/package.json)

**Comment by torquan** [comment]
having the same issue after updating the package to the current version.

**Comment by mhnpd** [comment]
Can you post project package configuration or a sandbox to recreate this problem

**Comment by 1trackprojects1** [comment]
I am having the exact same issue as well

**Comment by 1trackprojects1** [comment]
Here is my package.json if that helps:

`{
  "name": "REDACTED",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "12.0.9",
    "next-auth": "^4.2.0",
    "nprogress": "^0.2.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-loader-spinner": "^5.1.0"
  },
  "devDependencies": {
    "@types/next-auth": "^3.15.0",
    "@types/node": "17.0.13",
    "@types/nprogress": "^0.2.0",
    "@types/react": "17.0.38",
    "autoprefixer": "^10.4.2",
    "eslint": "8.8.0",
    "eslint-config-next": "12.0.9",
    "postcss": "^8.4.6",
    "tailwindcss": "^3.0.18",
    "typescript": "4.5.5"
  }
}
`

**Comment by es-ki** [comment]
@mhnpd 
I'm using Next.js.  
I have prepared a repository.  
https://github.com/Sakaki-Ya/loader-test

**Comment by Sysix** [comment]
Im sorry guys, I created that bug with my last PR. A new PR is open and ready to merge :)
