### ISSUE TITLE
NPM throws a warning on every package install after installing react-loader-spinner

### ISSUE THREAD

**Issue by clytras** [mhnpd/Test#125]
Hello and thanks for the awesome spinners!

After installing `react-loader-spinner`, I get an NPM warning on whatever package I try to install:

```
❯ npm i react
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'react-loader-spinner@6.0.0-0',
npm WARN EBADENGINE   required: { npm: 'please-use-yarn', yarn: '>= 1.19.1' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.5' }
npm WARN EBADENGINE }
```

This is very annoying and I'm currently patching the `react-loader-spinner/package.json` to purge the `engines` entry completely.

NPM: 8.5.5
Node: 16.14.0
react-loader-spinner: 6.0.0-0

**Comment by zadigg** [comment]
have u found any ways to solve this other than installing it using yarn?

**Comment by clytras** [comment]
@zadigg Unfortunately, no. Maybe using patch-package to patch `package.json` but I haven't tried that yet. I'm doing the patching using another script. This needs to fixed; it's annoying.

**Comment by mhnpd** [comment]
This issue is solve with new version.
