### ISSUE TITLE
RotatingLines spinner

### ISSUE THREAD

**Issue by rkreddy99** [mhnpd/Test#132]
Hi @mhnpd, in the webpage RotatingLines component is present (https://mhnpd.github.io/react-loader-spinner/rotating-lines), but the npm modules do not have it.

**Comment by MoRadwan74** [comment]
I don't know if it's missed by mistake or not but the component itself is not available in the code base.

Check the [loader directory](https://github.com/mhnpd/react-loader-spinner/tree/master/src/loader), it doesn't have the RotatingLines component.

**Comment by mhnpd** [comment]
This issue is fixed with version 5.2
