### ISSUE TITLE
Missing styles for Triangle spinner

### ISSUE THREAD

**Issue by MoRadwan74** [mhnpd/Test#133]
The Triangle component that is shown in the [docs](https://mhnpd.github.io/react-loader-spinner/triangle) is missing some styling for the `svg` and `polygon` tags as I can see from the [source code](https://github.com/mhnpd/react-loader-spinner/blob/v5.1.2/src/loader/Triangle.tsx).

I'd like to do a PR with the fix but I can't test if it's working as it should.

If you could provide me a guide on how to run it for development, it would be great!

Thanks, @mhnpd

**Comment by mhnpd** [comment]
Please refer:

https://github.com/mhnpd/react-loader-spinner/issues/124
