### ISSUE TITLE
Can't access css file with version 5.2

### ISSUE THREAD

**Issue by ronak-apparel** [mhnpd/Test#135]
Getting error while npm install after upgrading to version 5.2. Below error:
Module not found: Can't resolve 'react-loader-spinner/dist/loader/css/react-spinner-loader.css'

**Comment by atapas** [comment]
I am facing it too.

**Comment by mhnpd** [comment]
Css import is no longer required with this version. Simply remove css import to fix it.  

Should be a breaking changes [**Bug**: Publish a new version with major upgrade]

https://github.com/mhnpd/react-loader-spinner#usage

https://github.com/mhnpd/react-loader-spinner/issues/124
