### ISSUE TITLE
Export prop interfaces

### ISSUE THREAD

**Issue by alex-grover** [mhnpd/Test#142]
Hello, I'd like to be able to use the props defined in this package to write something like the following:

```tsx
import { Oval, OvalProps } from 'react-loader-spinner'

interface MyCustomLoaderProps extends OvalProps {
  custom: string
}

function MyCustomLoader({ custom, ...ovalProps }): JSX.Element {
  return (
    <div myotherthing={custom}>
      <Oval {...ovalProps} />
    </div>
  )
}
```

However, this currently isn't possible because `OvalProps` (and the other related interfaces) aren't exported. As far as I can tell this should be a fairly small change to export the interfaces from the loader files and then again in `src/index.ts`.

If this would be an acceptable change, I'm happy to submit a PR!

**Comment by mhnpd** [comment]
@alex-grover Sound like a valid proposal. Please fee free to raise a PR
