### ISSUE TITLE
Oval hardcoded padding

### ISSUE THREAD

**Issue by ChubbyDuck** [mhnpd/Test#153]
Hey! Is there a reason for [this line](https://github.com/mhnpd/react-loader-spinner/blob/4666190a00db1264535f57ee6843d318194cbf1a/src/loader/Oval.tsx#L58) to contain `{padding: 3}` ? 
Seems like a bug, makes impossible to adjust the wrapper padding for this component.

**Comment by osvaldokalvaitir** [comment]
I have the same problem
