### ISSUE TITLE
New update introducing code breaking changes

### ISSUE THREAD

**Issue by bennaaym** [mhnpd/Test#160]
Hello, I am currently using version `^5.4.5` of the "react-loader-spinner" package in my project. According to Semantic Versioning, this version specification should allow for any minor update less than `6.0.0` while maintaining backward compatibility.

However, it seems that there have been breaking changes in the latest release, impacting the existing functionality in my project. I fixed the error by removing ^ and installing version `5.4.5`

![image](https://github.com/mhnpd/react-loader-spinner/assets/68559207/5d30b20c-93f6-4770-b007-54bafba32b6d)

 I wanted to bring this to your attention in case it wasn't intentional or planned.

**Comment by kingsley-einstein** [comment]
I'm experiencing the same. I had to install 5.4.5

**Comment by mhnpd** [comment]
Thank you for bringing this to my attention. I hadn't realized that the import statements were impacted by the new library build method. I have made the necessary adjustments and released the changes as a major version. Please note that version 5.5.0 has been deprecated.
