### ISSUE TITLE
The prop wrapperClassName is not expected in typescript

### ISSUE THREAD

**Issue by mesuhailpm** [mhnpd/Test#164]
As per the documentation `wrapperClassName`  Is a prop expected. But when getting used with typescript getting warning 
`Type '{ height: string; width: string; radius: string; color: string; ariaLabel: string; wrapperStyle: {}; wrapperClassName: undefined; visible: true; wrapperClass: string; }' is not assignable to type 'IntrinsicAttributes & WatchProps'.
  Property 'wrapperClassName' does not exist on type 'IntrinsicAttributes & WatchProps'. Did you mean 'wrapperClass'?ts(2322)
`

**Comment by mhnpd** [comment]
fix with v6.1.6
