### ISSUE TITLE
All Examples Fail With Error Message

### ISSUE THREAD

**Issue by slimandslam** [mhnpd/Test#165]
MacOS 13.4.1 ARM with latest versions of Safari and Firefox.

On your examples page here:

https://mhnpd.github.io/react-loader-spinner/docs/category/components

On Safari, all examples fail with "SyntaxError: Cannot use the keyword 'default' as a parameter name."

On Firefox, all examples fail with "SyntaxError: missing formal parameter"

Example:

![Screenshot 2023-12-19 at 1 09 47 AM](https://github.com/mhnpd/react-loader-spinner/assets/229575/58b1fe2b-a3b5-4b36-9cab-56155c135390)

**Comment by tirathsharma098** [comment]
Same is happening in Chrome latest

**Comment by SAGARSINGH-1** [comment]
@mhnpd please resolve this issue

**Comment by mhnpd** [comment]
Fix with v6.1.6
