### ISSUE TITLE
Type error: Module '"react-loader-spinner"' has no exported member 'Grid'

### ISSUE THREAD

**Issue by reveurguy** [mhnpd/Test#166]
Hello
I am getting this error while deploying on vercel. Got this error with `version 5.4.5` as well as `version 6.1.1-0`.
Any updates regarding this issue or how can i solve this?
A lot of people have been getting this error recently.

<img width="1260" alt="Screenshot 2023-12-19 at 8 28 17 PM" src="https://github.com/mhnpd/react-loader-spinner/assets/59417546/939cc2ac-13bf-407e-a38d-f24f3568e8d0">

**Comment by akshay-nm** [comment]
I am getting
``` 
Module '"react-loader-spinner"' has no exported member 'ThreeDots'. Did you mean to use 'import ThreeDots from "react-loader-spinner"' instead?
```

**Comment by mhnpd** [comment]
Please use new version v6.1.6
